=== GeroVanMi/KeyKeeper/target/classes/xml/passwordSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">
    <xs:element name="passwords">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="username"/>
                            <xs:element name="password"/>
                            <xs:element name="mail"/>
                            <xs:element name="entry" maxOccurs="unbounded">
                                <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="website" type="xs:string"/>
                                    <xs:element name="password"/>
                                    <xs:element name="username"/>
                                </xs:sequence>
                                </xs:complexType>
                        </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GeroVanMi/KeyKeeper/target/classes/xml/passwords.xml
<?xml version="1.0" encoding="UTF-8"?>
<passwords xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="/Volumes/Freecom SSD/Module/aModul183Lanza/KeyKeeper/src/main/resources/xml/passwordSchema.xsd">
        <user>
            <username>Test</username>
            <password>1234</password>
            <mail>mail@mail.com</mail>
            <entry>
                <website>google.com</website>
                <password>cryption</password>
                <username>Bob</username>
            </entry>
            <entry>
                <website>kbw.ch</website>
                <password>1234_$</password>
                <username>natalie.breu</username>
            </entry>
            <entry>
                <website>github.ch</website>
                <password>banAnA5</password>
                <username>geroVanMi</username>
            </entry>
            <entry>
                <website>youtube.com</website>
                <password>trustno1</password>
                <username>no1</username>
            </entry>
            <entry>
                <website>quizlet.com</website>
                <password>password</password>
                <username>thisisjustaletter</username>
            </entry>
        </user>
    <user>
        <username>test</username>
        <password>MyUser</password>
        <mail>mail@testMail.com</mail>
        <entry>
            <website></website>
            <password></password>
            <username></username>
        </entry>
    </user>
</passwords>
